name = "ParticipationAnalytics"
uuid = "3bc74930-dab7-11e8-2241-453bb1e3974f"
authors = ["Lars Sch√ºtz"]
version = "0.1.0"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Languages = "8ef0a80b-9436-5d2c-a485-80b904378c43"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TextAnalysis = "a2db99b7-8b79-58f8-94bf-bbc811eef33d"

[compat]
Clustering = "0.14.2"
Distances = "0.10.0"
JSON = "0.21.1"
Languages = "0.4.3"
SQLite = "1.0.5"
Tables = "1.2.1"
TextAnalysis = "0.7.0"
julia = "1.5"
